### PR TITLE
Adds aditional Windows adapter metrics.

### PR DESCRIPTION
**Pull request by kdschlosser**
Default Gateways

DHCP enabled
DHCP server
DHCP lease acquired
DHCP lease renew

WINS enabled
WINS primary server
WINS secondary server

I am pretty sure that at least the gateways and DHCP stuff can also be gathered from non Windows based systems. unfortunately I do not know how to do do it. maybe someone else would be willing.

I added whatever it was that i could access from a script I had made. if you do not see a need for it then it can easily be removed. use some or part of or not at all. I do feel it would be extremely useful to have the gateway information at the very least.

my use case for the gateways would be enumerating UPNP devices on a network. not all routers will respond to a UPNP SSDP discovery packet if it is broadcast it has to be sent to the router IP directly.

### CODE REVIEW

**Comment by kdschlosser** [comment]
that was the big purpose for the PR was to see if someone had the missing parts from the other OS's.

and if you look closely the gateway is not a single item. it is a list and that list gets added to if matching networks are found. I do know that multiple gateways can be supplied. and this has accounted for that. it is also the reason i do not stop the iteration over the gateways when reading from the Structure as well as when doing the network match. the other bits. like the DHCP and WINS (i do not believe is used anymore and is simply there as a hood ornament so we have a constant reminder of yet another failed Microsoft accessory lol) are simply fluff there because it can be accessed.

As far as extending the Adapter and IP objects. I did it in a way that does not break API. so any code that was designed to run using the old mechanism will continue to work if these things were added. I was careful not to change the API.

for the most part besides some small variances in fields in the structures of the c objects between Linux flavors and OSX there is really only 2 OS API's that are going to vary in an extreme way. you will have Windows and then all others. 

I do not know if there are functions for obtaining the DHCP information as well as the gateway information in clib. I could code the rest of it if there was some source code of clib or any detailed documentation on it. i briefly searched but came up empty handed. I do have to admit I did not look that hard. 

I do have a question tho. I see the use of ipaddress.ip_address. but you use it to simply collect a string version of the IP. why did you not subclass ipaddress.IPv4Address and ipaddress.IPv6Interface?? actually better yet would be subclassing ipaddress.IPv4Interface ipaddress.IPv6Interface for the adapter class. this would extend a bunch of extra information. and it would also allow the user to be able to put some address into a class and to easily check if it is on the same network as one of the adapters on their machine. if there is something in the ipaddress module that does not work correctly or really is overkill and not necessary can be overridden to throw an exception. it would be worth it just for the equality testing alone but you also have properties like is_private, is_loopback, is_link_local and functions like subnet_of or supernet_of. The hosts function would be something that would be really handy if a user wants to connect to every host on a network.

**Comment by jstasiak** [comment]
@kdschlosser:

I'll have a look at the POSIX-way (hopefully the API varies minimally across operating systems) of fetching at least some of the extra data you fetch on Windows here. *But* it won't fully match the Windows-side, so I'm considering the following two scenarios:

* I figure out The Way to get the gateways on POSIX systems and limit your change to just gateways (as you mention DHCP and WINS info is just fluff that's there – we can bring it back easily later)
* All the new stuff gets put in an "extra" fields in `Adapter` and `IP` with an explicit note that no compatibility guarantees are provided for them and that the information provided may vary depend on the OS (Windows vs non-Windows)

I'm leaning towards the first one as I have concerns similar to @pydron's.

On your second point (strings vs using or subclassing `IPv*Addres/IPv*Interface` classes) – not sure what the original motivation was so I can't comment on that. I'm working on creating a new `addresses` property in the `Adapter` class that will return a list of instances of `IPv4Address` or `IPv6Interface` (I need to read the docs and educate myself on the details) and this should address your concerns here regarding having objects with useful methods on them as opposed to just text. The `ips` property will remain in place for now for backwards compatibility.

I intend to merge your change sooner rather than later, as I want to make some more changes to the codebase and I'd like to limit the number of merge conflicts to resolve. :)

**Comment by jstasiak** [comment]
So I rebased your branch on top of the current master and added some test code to print all the adapters and gateways on Windows to compare to what netifaces returns as I want to implement netifaces on top of ifaddr. This is the branch https://github.com/pydron/ifaddr/compare/dev-pr-15?expand=1 (6f84f4e088c848c84ba52db896d6d8382a7d5a4c is the tip at the moment). The code doesn't show any gateways on our side though (?):

```
ifaddr
======
Interfaces:
index 13 name {27FB9A68-6721-4324-AB80-57D275B96CFA}. Gateways:
IP-s:
* IP(ip=('fe80::bd2a:f1f7:b40b:786e', 0, 13), network_prefix=64, nice_name='Ethernet', gateways=[])
* IP(ip='10.1.0.4', network_prefix=16, nice_name='Ethernet', gateways=[])

index 1 name {AC287D57-914F-11EA-8D55-806E6F6E6963}. Gateways:
IP-s:
* IP(ip=('::1', 0, 0), network_prefix=128, nice_name='Loopback Pseudo-Interface 1', gateways=[])
* IP(ip='127.0.0.1', network_prefix=8, nice_name='Loopback Pseudo-Interface 1', gateways=[])

index 9 name {1BB67BBB-7EDA-45BA-AB72-64A712C5853E}. Gateways:
IP-s:
* IP(ip=('fe80::1de3:e7c7:d8a6:a646', 0, 9), network_prefix=64, nice_name='vEthernet (nat)', gateways=[])
* IP(ip='172.17.128.1', network_prefix=20, nice_name='vEthernet (nat)', gateways=[])


netifaces
=========
Interfaces:

{-1000: [{'addr': '00:0d:3a:fe:39:b9'}],
 2: [{'addr': '10.1.0.4',
      'broadcast': '10.1.255.255',
      'netmask': '255.255.0.0'}],
 23: [{'addr': 'fe80::bd2a:f1f7:b40b:786e%13',
       'broadcast': 'fe80::ffff:ffff:ffff:ffff%13',
       'netmask': 'ffff:ffff:ffff:ffff::/64'}]}

{-1000: [{'addr': ''}],
 2: [{'addr': '127.0.0.1',
      'broadcast': '127.255.255.255',
      'netmask': '255.0.0.0'}],
 23: [{'addr': '::1',
       'broadcast': '::1',
       'netmask': 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff/128'}]}

{-1000: [{'addr': '00:15:5d:b5:9c:db'}],
 2: [{'addr': '172.17.128.1',
      'broadcast': '172.17.143.255',
      'netmask': '255.255.240.0'}],
 23: [{'addr': 'fe80::1de3:e7c7:d8a6:a646%9',
       'broadcast': 'fe80::ffff:ffff:ffff:ffff%9',
       'netmask': 'ffff:ffff:ffff:ffff::/64'}]}


Gateways:
{2: [('10.1.0.1', '{27FB9A68-6721-4324-AB80-57D275B96CFA}', True)],
 'default': {2: ('10.1.0.1', '{27FB9A68-6721-4324-AB80-57D275B96CFA}')}}
```

What version of Windows have you run this on?

**Comment by kdschlosser** [comment]
HOLY COW!!!!.. This PR is really really old. LOL... I m going to have to look over it again to see what is up. What is the version of Windows you are running it on? That may have something to do with what gets found. Windows 10 is a complete mess in terms of the API. They very well could have change something about. I will go over the Windows SDK and see what I am able to find.

give me  day to take a look at it.

cool??

**Comment by jstasiak** [comment]
I feel you, it *is* really old. :) Yeah, sure, any help will be appreciated. I think it's Windows Server 2019, that's the one selected when the CI build runs on `windows-latest` in GitHub Actions (I don't have a Windows installation locally), this is the information reported in https://github.com/pydron/ifaddr/runs/751353019?check_suite_focus=true:

```
Operating System
  Microsoft Windows Server 2019
  10.0.17763
  Datacenter
```

I had a look at how `netifaces` reads things and they use `GetIPForwardTable2` and `GetIPForwardTable` (as a fallback).

**Comment by kdschlosser** [comment]
OK so i tested the code and this is the output from my machine.

```
Adapter(name=u'{C2E09D5E-13B1-4D9D-AA8C-17B77E8B92D4}', nice_name=u'Realtek PCIe GBE Family Controller', ips=[IP(ip=('fe80::6125:9fa:a509:ac45', 0L, 13L), network_prefix=64, nice_name=u'Local Area Connection 2', gateways=[]), IP(ip='192.168.1.21', network_prefix=24, nice_name=u'Local Area Connection 2', gateways=['192.168.1.1'])])
Adapter(name=u'{846EE342-7039-11DE-9D20-806E6F6E6963}', nice_name=u'Software Loopback Interface 1', ips=[IP(ip=('::1', 0L, 0L), network_prefix=128, nice_name=u'Loopback Pseudo-Interface 1', gateways=[]), IP(ip='127.0.0.1', network_prefix=8, nice_name=u'Loopback Pseudo-Interface 1', gateways=[])])
Adapter(name=u'{C70BE96A-A1CF-4313-AE4C-4F488C6B7726}', nice_name=u'Microsoft ISATAP Adapter', ips=[IP(ip=('fe80::5efe:c0a8:115', 0L, 12L), network_prefix=128, nice_name=u'isatap.{C2E09D5E-13B1-4D9D-AA8C-17B77E8B92D4}', gateways=[])])

```

the gateways does work. I have a suspicion that it may be because of DHCP and the information is not getting populated using the mechanism I am using. Check Adapter.dhcp_enabled and see what the result of that is.

I have a statically entered gateway.

**Comment by jstasiak** [comment]
I see, got it. Can you tell me what

```python
import netifaces
for interface in netifaces.interfaces():
    print(netifaces.ifaddresses(interface))
print()
print(netifaces.gateways())
```

show on your machine? Ideally I'd like to handle both the netifaces-like behaviour and, from what I understand is your use case, statically defined per-interface gateways.

**Comment by kdschlosser** [comment]
I am almost done porting the entire networking bits from the Windows SDK to Python. I should be done with it this evening. I have some errands to take car of for a few hours. When I get back I will finish it up. The Port is not something that is going to run. It can be used for reference and things like the structured copied out of it. It makes life easier is what it does. right now it is at 26651 lines of code and that is not something you want to add to this library. But it is going to contain the information we need to get this up and running properly.

If you can point me to the header files that are used in POSIX systems that handle the networking I am sure I can locate the components in it that would match up with the Windows versions. This would keep the API identical between OS's

**Comment by jstasiak** [comment]
I think I know how to implement the relevant bits on both Linux and Mac OS and have some code already working, I'll upload it some time this week and then we can see what's what API-wise.

On a different subject: wow, that's a lot of lines, are you porting some examples or implementing Python accessors to everything networking-related there is on Windows?

**Comment by kdschlosser** [comment]
Here. I have a whole lot more done I haven't done a push to the repo in a long while. But it gives you a basic idea of what I have done.

https://github.com/kdschlosser/pyWinAPI

**Comment by kdschlosser** [comment]
If you are dealing with anything Windows API related that is a great way to do a whole lot of copying and pasting to get the job done a lot faster. it is structured exactly like the Windows SDK is and it also has all of the pre-processor macros in place so adjustments needing to be made for things like the Windows version can be done.

**Comment by kdschlosser** [comment]
and here are the network portions of the API in case you want to use them as a reference. I did not include all of the "type" files so any data types you will need to go to the above mentioned repo and dig them out. Most of them should be in wtypes_h.py in the shared folder.

[windows_network_api.zip](https://github.com/pydron/ifaddr/files/4755499/windows_network_api.zip)

**Comment by kdschlosser** [comment]
Here is a better grouping of the networking related functions, structures and enumerations that you would need to facilitate all of the aspects of networking that you are dealing with in your library. It is organized by the same header file names used in the windows sdk so that should help if you ned to get more information on something.

I know there is going to be a bunch of things that you do not need in this but I figure I would make it as complete as possible and then you can pick out the bits you are going to use.

[networking_win_api.zip](https://github.com/pydron/ifaddr/files/4756504/networking_win_api.zip)

**Comment by kdschlosser** [comment]
Hey. I thought I would drop a line and tell you how far I have gotten.

here is the output of one of my adapters. it is formatted as json. I still have to get the ip addresses married to the interfaces but that shouldn't be to hard to do.

This should work whether or not the gateways are static or dynamic.
It also provides the dns server addresses as well as the address of the dhcp server as well (if one is used)
```json
{
        "dns_servers": [
            "8.8.8.8", 
            "8.8.4.4"
        ], 
        "dhcp_v6_server_address": null, 
        "dns_suffix": "", 
        "interfaces": [
            {
                "connection_type": Dedicated, 
                "physical_address": "BC:5F:F4:BC:B4:BD", 
                "description": "Realtek PCIe GBE Family Controller", 
                "rx_speed": 1000000000, 
                "default_gateway": "192.168.1.1", 
                "linklocal_behavior": Delayed, 
                "permanent_physical_address": "BC:5F:F4:BC:B4:BD", 
                "physical_media_type": UWB, 
                "router_discovery_behavior": DHCP, 
                "supports_wake_up": true, 
                "supports_router_discovery": true, 
                "alias": "Local Area Connection 2", 
                "connected": true, 
                "gateways": [
                    "192.168.1.1"
                ], 
                "media_type": 802.11, 
                "tx_speed": 1000000000, 
                "supports_neighbor_discovery": true
            }, 
            {
                "connection_type": Dedicated, 
                "physical_address": "BC:5F:F4:BC:B4:BD", 
                "description": "Realtek PCIe GBE Family Controller", 
                "rx_speed": 1000000000, 
                "default_gateway": "192.168.1.1", 
                "linklocal_behavior": Always On, 
                "permanent_physical_address": "BC:5F:F4:BC:B4:BD", 
                "physical_media_type": UWB, 
                "router_discovery_behavior": Enabled, 
                "supports_wake_up": true, 
                "supports_router_discovery": true, 
                "alias": "Local Area Connection 2", 
                "connected": true, 
                "gateways": [
                    "192.168.1.1"
                ], 
                "media_type": 802.11, 
                "tx_speed": 1000000000, 
                "supports_neighbor_discovery": true
            }
        ], 
        "ip_adresses": [
            [
                "", 
                0, 
                13
            ], 
            "192.168.1.21"
        ], 
        "friendly_name": "Local Area Connection 2", 
        "nice_name": "Realtek PCIe GBE Family Controller", 
        "dhcp_v4_server_address": null, 
        "gateways": [
            "192.168.1.1"
        ], 
        "guid": "{C2E09D5E-13B1-4D9D-AA8C-17B77E8B92D4}", 
        "ipv6_enabled": true, 
        "ipv4_enabled": true
    }, 
```

**Comment by kdschlosser** [comment]
OK so I have sorted out getting the IP addresses for an adapter and marring them to their proper interface thus allowing me to pair them with their respected gateways dns servers and what have you


```json
{
        "nice_name": "Realtek PCIe GBE Family Controller", 
        "ipv4_enabled": true, 
        "ipv6_enabled": true, 
        "dns_suffix": "", 
        "interfaces": [
            {
                "connection_type": "", 
                "dns_addresses": [], 
                "description": "", 
                "rx_speed": -1, 
                "default_gateway": null, 
                "linklocal_behavior": "", 
                "physical_media_type": "", 
                "router_discovery_behavior": "", 
                "supports_wake_up": false, 
                "supports_router_discovery": false, 
                "alias": "", 
                "connected": false, 
                "gateways": [], 
                "media_type": "", 
                "tx_speed": -1, 
                "dhcp_server": null, 
                "ip_address": {
                    "stack_version": "ipv6", 
                    "scope_id": 13, 
                    "ip_address": "", 
                    "flow_info": 0
                }, 
                "supports_neighbor_discovery": false
            }, 
            {
                "connection_type": Dedicated, 
                "dns_addresses": [
                    {
                        "stack_version": "ipv4", 
                        "ip_address": "8.8.8.8"
                    }, 
                    {
                        "stack_version": "ipv4", 
                        "ip_address": "8.8.4.4"
                    }
                ], 
                "physical_address": "BC:5F:F4:BC:B4:BD", 
                "description": "Realtek PCIe GBE Family Controller", 
                "rx_speed": 1000000000, 
                "default_gateway": {
                    "stack_version": "ipv4", 
                    "ip_address": "192.168.1.1"
                }, 
                "linklocal_behavior": Delayed, 
                "permanent_physical_address": "BC:5F:F4:BC:B4:BD", 
                "physical_media_type": UWB, 
                "router_discovery_behavior": DHCP, 
                "supports_wake_up": true, 
                "supports_router_discovery": true, 
                "alias": "Local Area Connection 2", 
                "connected": true, 
                "gateways": [
                    {
                        "stack_version": "ipv4", 
                        "ip_address": "192.168.1.1"
                    }
                ], 
                "media_type": 802.11, 
                "tx_speed": 1000000000, 
                "dhcp_server": null, 
                "ip_address": {
                    "stack_version": "ipv4", 
                    "ip_address": "192.168.1.21"
                }, 
                "supports_neighbor_discovery": true
            }
        ], 
        "guid": "{C2E09D5E-13B1-4D9D-AA8C-17B77E8B92D4}", 
        "friendly_name": "Local Area Connection 2"
    }, 
```

**Comment by jstasiak** [comment]
I got caught up in some other stuff – I'll try to get back to this issue ASAP, and yes, I'll implement the Linux and Mac side, hopefully it'll also cover other BSD-s and Solaris/Illumos with some minor modifications.

**Comment by kdschlosser** [comment]
Oh I just threw in a bunch of stuff for the hell of it. messing about and learning to see what is available.

In the example above I am checking for the existence of a gateway 2 different ways. The first way is how it is being done in this PR. This appears to only work if the gateway has been statically set. The other way is how netifaces does it and checks the routing tables.

**Pull request closed without merging**
